language: r
sudo: required

r:
  - oldrel
  - release
  - devel
cache: packages

# need this for current nlme:
r_packages:
  - nlme


after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
     
    on_success: change
    on_failure: always
